# Generated by Django 5.2.6 on 2025-10-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('short_description', models.CharField(max_length=255, verbose_name='توضیح کوتاه')),
                ('content', models.TextField(verbose_name='توضیح کامل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'مطلب',
                'verbose_name_plural': 'مطالب',
                'ordering': ['-created_at'],
            },
        ),
    ]
