# Generated by Django 5.2.6 on 2025-10-20 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration', models.PositiveIntegerField(null=True, verbose_name='مدت هر نوبت (دقیقه)')),
                ('lead_time', models.TimeField(null=True, verbose_name='زمان شروع کار')),
                ('finish_time', models.TimeField(null=True, verbose_name='زمان پایان کار')),
                ('appointment_buffer_time', models.PositiveIntegerField(default=0, verbose_name='زمان بافر نوبت (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی سرویس',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای سرویس',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام سرویس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('down_payment', models.PositiveIntegerField(default=0, verbose_name='بیعانه (تومان)')),
                ('duration', models.DurationField(verbose_name='مدت زمان')),
                ('payment_type', models.CharField(choices=[('full', 'پرداخت کامل'), ('down', 'بیعانه')], default='full', max_length=4, verbose_name='نوع پرداخت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='booking.servicecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_on_saturday', models.BooleanField(default=False)),
                ('work_on_sunday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services_offered', models.ManyToManyField(to='booking.service', verbose_name='خدمات ارائه شده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='قیمت کل')),
                ('payment_type', models.CharField(choices=[('full', 'پرداخت کامل'), ('down', 'بیعانه')], default='full', max_length=4, verbose_name='نوع پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('want_reminder', models.BooleanField(default=True, verbose_name='ارسال پیام یادآوری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.service', verbose_name='سرویس')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.staffmember', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.staffmember', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'unique_together': {('staff_member', 'day_of_week')},
            },
        ),
    ]
