# Generated by Django 5.2.6 on 2025-10-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='work_on_friday',
            field=models.BooleanField(default=False, verbose_name='جمعه'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='work_on_monday',
            field=models.BooleanField(default=False, verbose_name='دوشنبه'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='work_on_thursday',
            field=models.BooleanField(default=False, verbose_name='پنج\u200cشنبه'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='work_on_tuesday',
            field=models.BooleanField(default=False, verbose_name='سه\u200cشنبه'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='work_on_wednesday',
            field=models.BooleanField(default=False, verbose_name='چهارشنبه'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='work_on_saturday',
            field=models.BooleanField(default=False, verbose_name='شنبه'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='work_on_sunday',
            field=models.BooleanField(default=False, verbose_name='یکشنبه'),
        ),
    ]
