# Generated by Django 5.2.6 on 2025-10-27 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_staffmember_work_on_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 0), verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='ساعت شروع'),
        ),
    ]
