# Generated by Django 5.2.6 on 2025-10-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_workinghours_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='برای اطلاع\u200cرسانی پیامکی', max_length=15, null=True, verbose_name='شماره تماس مشتری'),
        ),
    ]
