# Generated by Django 5.2.6 on 2025-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='followup_days',
            field=models.PositiveIntegerField(default=0, help_text='مثلا 30،یعنی سی روز بعد از انجام سرویس', verbose_name='روزهای یادآوری'),
        ),
        migrations.AddField(
            model_name='service',
            name='has_followup',
            field=models.BooleanField(default=False, verbose_name='نیاز به پیام یادآوری ترمیم دارد؟'),
        ),
    ]
